Repository ISIS3510-202320-Team31/Android-Kotlin, pull requests merged in 2023-12, with the labels that each got.

#83 No internet main activity
  app/src/main/java/com/example/hive/view/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: bug

#87 Feature/stats view #75
  app/build.gradle
  app/src/main/java/com/example/hive/model/adapters/PartnerNamesAdapter.kt
  app/src/main/java/com/example/hive/model/network/ApiInterface.kt
  app/src/main/java/com/example/hive/model/network/responses/CategoryResponse.kt
  app/src/main/java/com/example/hive/model/network/responses/TopPartnersResponse.kt
  app/src/main/java/com/example/hive/model/repository/UserRepository.kt
  app/src/main/java/com/example/hive/model/room/HiveDatabase.kt
  app/src/main/java/com/example/hive/model/room/daos/CategoryChartDao.kt
  app/src/main/java/com/example/hive/model/room/daos/TopPartnersDao.kt
  app/src/main/java/com/example/hive/model/room/entities/CategoryChart.kt
  app/src/main/java/com/example/hive/model/room/entities/TopPartners.kt
  app/src/main/java/com/example/hive/view/EstadisticsFragment.kt
  app/src/main/java/com/example/hive/view/UserProfileFragment.kt
  app/src/main/java/com/example/hive/viewmodel/UserProfileOfflineViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/UserProfileOfflineViewModelProviderFactory.kt
  app/src/main/java/com/example/hive/viewmodel/UserProfileViewModel.kt
  app/src/main/res/layout/fragment_estadistics.xml
  app/src/main/res/layout/fragment_user_profile.xml
  app/src/main/res/layout/item_name_partner.xml
  app/src/main/res/values/strings.xml
  settings.gradle
Labels: enhancement

#88 Feature/filter by category #78
  app/src/main/java/com/example/hive/view/HomePageFragment.kt
  app/src/main/res/layout/fragment_home_page.xml
  app/src/main/res/values/spinner_signup.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#89 Feature/bee on tap #80
  .idea/assetWizardSettings.xml
  app/build.gradle
  app/src/main/java/com/example/hive/model/adapters/SessionManager.kt
  app/src/main/java/com/example/hive/model/room/daos/EventUserDao.kt
  app/src/main/java/com/example/hive/view/BeeView.kt
  app/src/main/java/com/example/hive/view/CustomScrollView.kt
  app/src/main/java/com/example/hive/view/UserProfileFragment.kt
  app/src/main/res/drawable/bee_icon.png
  app/src/main/res/drawable/round_grey_2.xml
  app/src/main/res/layout/fragment_user_profile.xml
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#91 Feature/micro optimizations #90
  app/src/main/java/com/example/hive/model/adapters/CalendarHistoricalAdapter.kt
  app/src/main/java/com/example/hive/model/adapters/EventsAdapter.kt
  app/src/main/java/com/example/hive/model/adapters/PartnerNamesAdapter.kt
  app/src/main/java/com/example/hive/model/adapters/SessionManager.kt
  app/src/main/java/com/example/hive/model/adapters/TopCreatorsAdapter.kt
  app/src/main/java/com/example/hive/model/repository/UserRepository.kt
  app/src/main/java/com/example/hive/view/BeeView.kt
  app/src/main/java/com/example/hive/view/CalendarActivitiesFragment.kt
  app/src/main/java/com/example/hive/view/CalendarCreadosFragment.kt
  app/src/main/java/com/example/hive/view/CalendarFragment.kt
  app/src/main/java/com/example/hive/view/CalendarHistoricalFragment.kt
  app/src/main/java/com/example/hive/view/EstadisticsFragment.kt
  app/src/main/java/com/example/hive/view/EventDetailFragment.kt
  app/src/main/java/com/example/hive/view/HomePageFragment.kt
  app/src/main/java/com/example/hive/view/LoginFragment.kt
  app/src/main/java/com/example/hive/view/TopCreatorsFragment.kt
  app/src/main/java/com/example/hive/view/UserProfileFragment.kt
  app/src/main/java/com/example/hive/viewmodel/AddParticipatEventViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/CalendarListViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/EventCreationViewModelProviderFactory.kt
  app/src/main/java/com/example/hive/viewmodel/EventDetailViewModelProviderFactory.kt
  app/src/main/java/com/example/hive/viewmodel/EventListOfflineViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/EventListOfflineViewModelProviderFactory.kt
  app/src/main/java/com/example/hive/viewmodel/EventListViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/TopCreatorsOfflineViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/TopCreatorsOfflineViewModelProviderFactory.kt
  app/src/main/java/com/example/hive/viewmodel/TopCreatorsViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/TopCreatorsViewModelProviderFactory.kt
  app/src/main/java/com/example/hive/viewmodel/UserProfileOfflineViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/UserProfileViewModel.kt
Labels: documentation, enhancement
