Repository ISIS3510-202320-Team31/Android-Kotlin, pull requests merged in 2023-11, with the labels that each got.

#52 Validations
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/hive/view/EventCreationFragment.kt
  app/src/main/java/com/example/hive/view/SignUpActivity.kt
  app/src/main/res/layout/fragment_event_creation.xml
  app/src/main/res/layout/fragment_event_detail.xml
  app/src/main/res/layout/fragment_sign_up.xml
Labels: bug

#53 Fix repository
  app/src/main/java/com/example/hive/view/CalendarActivitiesFragment.kt
  app/src/main/java/com/example/hive/view/CalendarHistoricalFragment.kt
  app/src/main/java/com/example/hive/view/EventCreationFragment.kt
  app/src/main/java/com/example/hive/view/EventDetailFragment.kt
  app/src/main/java/com/example/hive/view/HomePageFragment.kt
  app/src/main/java/com/example/hive/view/LoginActivity.kt
  app/src/main/java/com/example/hive/view/LoginFragment.kt
  app/src/main/java/com/example/hive/view/SignUpActivity.kt
  app/src/main/java/com/example/hive/view/SignUpFragment.kt
  app/src/main/java/com/example/hive/view/UserProfileFragment.kt
  app/src/main/java/com/example/hive/viewmodel/AddParticipatEventViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/AddParticipatEventViewModelProviderFactory.kt
  app/src/main/java/com/example/hive/viewmodel/CalendarListViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/CalendarViewModelProviderFactory.kt
  app/src/main/java/com/example/hive/viewmodel/EventCreationViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/EventCreationViewModelProviderFactory.kt
  app/src/main/java/com/example/hive/viewmodel/EventListViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/EventsViewModelProviderFactory.kt
  app/src/main/java/com/example/hive/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/LoginViewModelProviderFactory.kt
  app/src/main/java/com/example/hive/viewmodel/SignUpViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/SignUpViewModelProviderFactory.kt
  app/src/main/java/com/example/hive/viewmodel/UserProfileViewModel.kt
  app/src/main/java/com/example/hive/viewmodel/UserProfileViewModelProviderFactory.kt
  app/src/main/res/layout/fragment_event_creation.xml
Labels: bug

#54 Hotfix/fix detail event view #44
  app/src/main/java/com/example/hive/model/adapters/EventsAdapter.kt
  app/src/main/java/com/example/hive/view/HomePageFragment.kt
  app/src/main/res/layout/fragment_event_detail.xml
  app/src/main/res/layout/progress_bar.xml
Labels: bug

#56 Hotfix/hardcoded strings #48
  app/src/main/java/com/example/hive/model/adapters/CalendarActivitiesAdapter.kt
  app/src/main/java/com/example/hive/model/adapters/CalendarHistoricalAdapter.kt
  app/src/main/java/com/example/hive/model/adapters/EventsAdapter.kt
  app/src/main/java/com/example/hive/view/EventCreationFragment.kt
  app/src/main/java/com/example/hive/view/HomePageFragment.kt
  app/src/main/java/com/example/hive/view/LocationMonitoringService.kt
  app/src/main/java/com/example/hive/view/LoginActivity.kt
  app/src/main/java/com/example/hive/view/LoginFragment.kt
  app/src/main/java/com/example/hive/view/MainActivity.kt
  app/src/main/java/com/example/hive/view/SignUpActivity.kt
  app/src/main/java/com/example/hive/view/SignUpFragment.kt
  app/src/main/java/com/example/hive/view/UserProfileFragment.kt
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/values/strings.xml
Labels: invalid

#58 Profile view fixed
  app/src/main/res/layout/fragment_user_profile.xml
Labels: invalid

#60 Feature/pull refresh #51
  app/build.gradle
  app/src/main/java/com/example/hive/view/HomePageFragment.kt
  app/src/main/java/com/example/hive/view/MainActivity.kt
  app/src/main/java/com/example/hive/view/UserProfileFragment.kt
  app/src/main/java/com/example/hive/viewmodel/EventListViewModel.kt
  app/src/main/res/layout/fragment_home_page.xml
  app/src/main/res/layout/fragment_user_profile.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#67 Secure Data implemented
  app/build.gradle
  app/src/main/java/com/example/hive/model/adapters/SessionManager.kt
  app/src/main/java/com/example/hive/view/LocationMonitoringService.kt
Labels: bug, enhancement

#72 forms, caching and calendar fix
  app/src/main/java/com/example/hive/util/FormProgressCache.kt
  app/src/main/java/com/example/hive/view/EventCreationFragment.kt
  app/src/main/java/com/example/hive/view/LoginActivity.kt
  app/src/main/java/com/example/hive/view/SignUpActivity.kt
  app/src/main/res/layout/fragment_event_creation.xml
Labels: bug, enhancement

#76 Local Storage Create Event
  app/src/main/java/com/example/hive/view/EventCreationFragment.kt
  app/src/main/java/com/example/hive/view/MainActivity.kt
Labels: bug
